const data = [
    'College of Engineering Building',
    'CME/COE Building',
    'Education Building',
    'Graduate School Building',
    'Bistro',
    'University Canteen',
    'Stage',
    'College of Technology/ COT Building',
    'Old Admin Building',
    'New Admin Building',
    'Student Activity Center',
    'Fitness Gym',
    'Sewing Area',
    'Fablab',
    'Tennis Court',
    'Kadasig Gym',
    'Oval',
    'Grandstand',
    'Study Area',
    'Existing Academic Science Building',
    'Cultural Center',
    'Floating Classroom',
    'CTU Facility Centrum',
    'HM Laboratory',
    'Mens Dorm',
    'Women Dorm',
    'Furniture Workshop',
    'Security Office',
    'ERRC Building',
]